"""Purpose-tagged multilingual cues. Variants exist only with a semantic reason."""

from __future__ import annotations

from backend.services.content.semantic_vocab.types import VocabEntry

# Canonical topic / scope / unsupported IDs (language-independent).
TOPIC_OVERVIEW = "overview"
TOPIC_HOD = "hod"
TOPIC_FEES = "fees"
TOPIC_ACHIEVEMENTS = "achievements"
TOPIC_PLACEMENTS = "placements"
TOPIC_FACULTY = "faculty"
TOPIC_CONTACT = "contact"
SCOPE_FULL = "full_department"
SCOPE_SINGLE = "single"
UNSUPPORTED_BUS = "bus"
UNSUPPORTED_DOCUMENTS = "documents"

_ENTRIES: tuple[VocabEntry, ...] = (
    # --- CAMPUS NAVIGATION intent (shared six-language semantic vocabulary) ---
    # These entries describe the user's goal independently from the destination.
    # Destination identity continues to come from the canonical campus map.
    VocabEntry("navigate", "en", "where is", "NAVIGATION_INTENT", "location_question"),
    VocabEntry("navigate", "en", "where are", "NAVIGATION_INTENT", "location_question"),
    VocabEntry("navigate", "en", "where can i find", "NAVIGATION_INTENT", "location_question"),
    VocabEntry("navigate", "en", "where", "NAVIGATION_INTENT", "location_question_short"),
    VocabEntry("navigate", "en", "how do i get to", "NAVIGATION_INTENT", "route_question"),
    VocabEntry("navigate", "en", "how to get to", "NAVIGATION_INTENT", "route_question"),
    VocabEntry("navigate", "en", "how do i reach", "NAVIGATION_INTENT", "route_question"),
    VocabEntry("navigate", "en", "how to reach", "NAVIGATION_INTENT", "route_question"),
    VocabEntry("navigate", "en", "directions to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "direction to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "take me to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "navigate to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "guide me to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "show me the way", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "which floor", "NAVIGATION_INTENT", "floor_question"),
    VocabEntry("navigate", "en", "locate", "NAVIGATION_INTENT", "location_request"),
    VocabEntry("navigate", "en", "find room", "NAVIGATION_INTENT", "location_request"),
    VocabEntry("navigate", "en", "path to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "route to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "i need to go to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "en", "i want to go to", "NAVIGATION_INTENT", "route_request"),
    VocabEntry("navigate", "kn", "ಎಲ್ಲಿ ಇದೆ", "NAVIGATION_INTENT", "kannada_location_question"),
    VocabEntry("navigate", "kn", "ಎಲ್ಲಿದೆ", "NAVIGATION_INTENT", "kannada_location_question"),
    VocabEntry("navigate", "kn", "ಎಲ್ಲಿ", "NAVIGATION_INTENT", "kannada_where"),
    VocabEntry("navigate", "kn", "ಹೇಗೆ ಹೋಗಬೇಕು", "NAVIGATION_INTENT", "kannada_route_question"),
    VocabEntry("navigate", "kn", "ಹೇಗೆ ಹೋಗುವುದು", "NAVIGATION_INTENT", "kannada_route_question"),
    VocabEntry("navigate", "kn", "ದಾರಿ ತೋರಿಸು", "NAVIGATION_INTENT", "kannada_route_request"),
    VocabEntry("navigate", "kn", "ತೋರಿಸು", "NAVIGATION_INTENT", "kannada_show"),
    VocabEntry("navigate", "*", "elli ide", "NAVIGATION_INTENT", "kannada_romanized_where"),
    VocabEntry("navigate", "*", "ellide", "NAVIGATION_INTENT", "kannada_romanized_where"),
    VocabEntry("navigate", "*", "elli", "NAVIGATION_INTENT", "kannada_romanized_where"),
    VocabEntry("navigate", "*", "yelli ide", "NAVIGATION_INTENT", "kannada_romanized_where_stt"),
    VocabEntry("navigate", "*", "yallide", "NAVIGATION_INTENT", "kannada_romanized_where_stt"),
    VocabEntry("navigate", "*", "hege hogbeku", "NAVIGATION_INTENT", "kannada_romanized_route"),
    VocabEntry("navigate", "*", "hege hogabeku", "NAVIGATION_INTENT", "kannada_romanized_route"),
    VocabEntry("navigate", "*", "heg hogbeku", "NAVIGATION_INTENT", "kannada_stt_route"),
    VocabEntry("navigate", "*", "torisu", "NAVIGATION_INTENT", "kannada_romanized_show"),
    VocabEntry("navigate", "hi", "कहाँ है", "NAVIGATION_INTENT", "hindi_location_question"),
    VocabEntry("navigate", "hi", "कहां है", "NAVIGATION_INTENT", "hindi_location_question"),
    VocabEntry("navigate", "hi", "कहाँ", "NAVIGATION_INTENT", "hindi_where"),
    VocabEntry("navigate", "hi", "कहां", "NAVIGATION_INTENT", "hindi_where"),
    VocabEntry("navigate", "hi", "कैसे जाना", "NAVIGATION_INTENT", "hindi_route_question"),
    VocabEntry("navigate", "hi", "रास्ता दिखाओ", "NAVIGATION_INTENT", "hindi_route_request"),
    VocabEntry("navigate", "hi", "दिखाओ", "NAVIGATION_INTENT", "hindi_show"),
    VocabEntry("navigate", "*", "kaha hai", "NAVIGATION_INTENT", "hindi_romanized_where"),
    VocabEntry("navigate", "*", "kahan hai", "NAVIGATION_INTENT", "hindi_romanized_where"),
    VocabEntry("navigate", "*", "kidhar hai", "NAVIGATION_INTENT", "hindi_romanized_where"),
    VocabEntry("navigate", "*", "kaise jana", "NAVIGATION_INTENT", "hindi_romanized_route"),
    VocabEntry("navigate", "*", "kaise jana hai", "NAVIGATION_INTENT", "hindi_romanized_route"),
    VocabEntry("navigate", "*", "dikhao", "NAVIGATION_INTENT", "hindi_romanized_show"),
    VocabEntry("navigate", "te", "ఎక్కడ ఉంది", "NAVIGATION_INTENT", "telugu_location_question"),
    VocabEntry("navigate", "te", "ఎక్కడ", "NAVIGATION_INTENT", "telugu_where"),
    VocabEntry("navigate", "te", "ఎలా వెళ్లాలి", "NAVIGATION_INTENT", "telugu_route_question"),
    VocabEntry("navigate", "te", "ఎలా వెళ్ళాలి", "NAVIGATION_INTENT", "telugu_route_question_stt"),
    VocabEntry("navigate", "te", "దారి చూపించు", "NAVIGATION_INTENT", "telugu_route_request"),
    VocabEntry("navigate", "te", "చూపించు", "NAVIGATION_INTENT", "telugu_show"),
    VocabEntry("navigate", "*", "ekkada undi", "NAVIGATION_INTENT", "telugu_romanized_where"),
    VocabEntry("navigate", "*", "ekkada", "NAVIGATION_INTENT", "telugu_romanized_where"),
    VocabEntry("navigate", "*", "ela vellali", "NAVIGATION_INTENT", "telugu_romanized_route"),
    VocabEntry("navigate", "*", "chupinchu", "NAVIGATION_INTENT", "telugu_romanized_show"),
    VocabEntry("navigate", "ta", "எங்கே இருக்கிறது", "NAVIGATION_INTENT", "tamil_location_question"),
    VocabEntry("navigate", "ta", "எங்கே", "NAVIGATION_INTENT", "tamil_where"),
    VocabEntry("navigate", "ta", "எப்படி போவது", "NAVIGATION_INTENT", "tamil_route_question"),
    VocabEntry("navigate", "ta", "எப்படி செல்வது", "NAVIGATION_INTENT", "tamil_route_question"),
    VocabEntry("navigate", "ta", "வழி காட்டுங்கள்", "NAVIGATION_INTENT", "tamil_route_request"),
    VocabEntry("navigate", "ta", "காட்டுங்கள்", "NAVIGATION_INTENT", "tamil_show"),
    VocabEntry("navigate", "*", "enga irukku", "NAVIGATION_INTENT", "tamil_romanized_where"),
    VocabEntry("navigate", "*", "enga", "NAVIGATION_INTENT", "tamil_romanized_where"),
    VocabEntry("navigate", "*", "enge", "NAVIGATION_INTENT", "tamil_romanized_where"),
    VocabEntry("navigate", "*", "eppadi povathu", "NAVIGATION_INTENT", "tamil_romanized_route"),
    VocabEntry("navigate", "*", "epdi povathu", "NAVIGATION_INTENT", "tamil_stt_route"),
    VocabEntry("navigate", "*", "epdi poganum", "NAVIGATION_INTENT", "tamil_stt_route"),
    VocabEntry("navigate", "*", "kaattunga", "NAVIGATION_INTENT", "tamil_romanized_show"),
    VocabEntry("navigate", "ml", "എവിടെയാണ്", "NAVIGATION_INTENT", "malayalam_location_question"),
    VocabEntry("navigate", "ml", "എവിടെ", "NAVIGATION_INTENT", "malayalam_where"),
    VocabEntry("navigate", "ml", "എങ്ങനെ പോകാം", "NAVIGATION_INTENT", "malayalam_route_question"),
    VocabEntry("navigate", "ml", "വഴി കാണിക്കൂ", "NAVIGATION_INTENT", "malayalam_route_request"),
    VocabEntry("navigate", "ml", "കാണിക്കൂ", "NAVIGATION_INTENT", "malayalam_show"),
    VocabEntry("navigate", "*", "evideyaanu", "NAVIGATION_INTENT", "malayalam_romanized_where"),
    VocabEntry("navigate", "*", "evide", "NAVIGATION_INTENT", "malayalam_romanized_where"),
    VocabEntry("navigate", "*", "engane pokam", "NAVIGATION_INTENT", "malayalam_romanized_route"),
    VocabEntry("navigate", "*", "kanikku", "NAVIGATION_INTENT", "malayalam_romanized_show"),

    # --- CAMPUS destination vocabulary (canonical English tokens / room codes) ---
    # Longest-span replacement lets native and mixed phrases enter the same room
    # matcher without creating a parser or destination registry per language.
    VocabEntry("B-004", "kn", "ಪ್ರಾಂಶುಪಾಲರ ಕಚೇರಿ", "CAMPUS_DESTINATION", "principal_office"),
    VocabEntry("B-004", "kn", "ಪ್ರಿನ್ಸಿಪಲ್ ಆಫೀಸ್", "CAMPUS_DESTINATION", "principal_office_loanword"),
    VocabEntry("B-004", "hi", "प्राचार्य कार्यालय", "CAMPUS_DESTINATION", "principal_office"),
    VocabEntry("B-004", "hi", "प्रिंसिपल ऑफिस", "CAMPUS_DESTINATION", "principal_office_loanword"),
    VocabEntry("B-004", "te", "ప్రిన్సిపల్ ఆఫీస్", "CAMPUS_DESTINATION", "principal_office_loanword"),
    VocabEntry("B-004", "te", "ప్రిన్సిపాల్ కార్యాలయం", "CAMPUS_DESTINATION", "principal_office"),
    VocabEntry("B-004", "ta", "முதல்வர் அலுவலகம்", "CAMPUS_DESTINATION", "principal_office"),
    VocabEntry("B-004", "ta", "பிரின்சிபல் ஆபிஸ்", "CAMPUS_DESTINATION", "principal_office_loanword"),
    VocabEntry("B-004", "ml", "പ്രിൻസിപ്പൽ ഓഫീസ്", "CAMPUS_DESTINATION", "principal_office_loanword"),
    VocabEntry("C-003", "kn", "ಗ್ರಂಥಾಲಯ", "CAMPUS_DESTINATION", "library"),
    VocabEntry("C-003", "hi", "पुस्तकालय", "CAMPUS_DESTINATION", "library"),
    VocabEntry("C-003", "te", "గ్రంథాలయం", "CAMPUS_DESTINATION", "library"),
    VocabEntry("C-003", "ta", "நூலகம்", "CAMPUS_DESTINATION", "library"),
    VocabEntry("C-003", "ml", "ലൈബ്രറി", "CAMPUS_DESTINATION", "library"),
    VocabEntry("B-011", "kn", "ಪ್ರವೇಶ ಕಚೇರಿ", "CAMPUS_DESTINATION", "admission_office"),
    VocabEntry("B-011", "hi", "प्रवेश कार्यालय", "CAMPUS_DESTINATION", "admission_office"),
    VocabEntry("B-011", "te", "ప్రవేశ కార్యాలయం", "CAMPUS_DESTINATION", "admission_office"),
    VocabEntry("B-011", "ta", "சேர்க்கை அலுவலகம்", "CAMPUS_DESTINATION", "admission_office"),
    VocabEntry("B-011", "ml", "പ്രവേശന ഓഫീസ്", "CAMPUS_DESTINATION", "admission_office"),
    # Landmark loanwords only (not principal cabin — that is CAMPUS_TERM + English aliases).
    VocabEntry("C-003", "kn", "ಲೈಬ್ರರಿ", "CAMPUS_DESTINATION", "library_loanword"),
    VocabEntry("C-003", "hi", "लाइब्रेरी", "CAMPUS_DESTINATION", "library_loanword"),
    VocabEntry("C-003", "te", "లైబ్రరీ", "CAMPUS_DESTINATION", "library_loanword"),
    VocabEntry("C-003", "ta", "லைப்ரரி", "CAMPUS_DESTINATION", "library_loanword"),
    VocabEntry("C-007", "kn", "ಸೆಮಿನಾರ್ ಹಾಲ್", "CAMPUS_DESTINATION", "seminar_hall_loanword"),
    VocabEntry("C-007", "hi", "सेमिनार हॉल", "CAMPUS_DESTINATION", "seminar_hall_loanword"),
    VocabEntry("C-007", "te", "సెమినార్ హాల్", "CAMPUS_DESTINATION", "seminar_hall_loanword"),
    VocabEntry("C-007", "ta", "செமினார் ஹால்", "CAMPUS_DESTINATION", "seminar_hall_loanword"),
    VocabEntry("C-007", "ml", "സെമിനാർ ഹാൾ", "CAMPUS_DESTINATION", "seminar_hall_loanword"),

    # --- Shared CAMPUS_TERM lexicon (rewrites to English tokens for all-room scoring) ---
    VocabEntry("lab", "kn", "ಪ್ರಯೋಗಾಲಯ", "CAMPUS_TERM", "lab"),
    VocabEntry("lab", "kn", "ಲ್ಯಾಬ್", "CAMPUS_TERM", "lab_loanword"),
    VocabEntry("lab", "hi", "प्रयोगशाला", "CAMPUS_TERM", "lab"),
    VocabEntry("lab", "hi", "लैब", "CAMPUS_TERM", "lab_loanword"),
    VocabEntry("lab", "te", "ప్రయోగశాల", "CAMPUS_TERM", "lab"),
    VocabEntry("lab", "te", "ల్యాబ్", "CAMPUS_TERM", "lab_loanword"),
    VocabEntry("lab", "ta", "ஆய்வகம்", "CAMPUS_TERM", "lab"),
    VocabEntry("lab", "ta", "லேப்", "CAMPUS_TERM", "lab_loanword"),
    VocabEntry("lab", "ml", "ലബോറട്ടറി", "CAMPUS_TERM", "lab"),
    VocabEntry("lab", "ml", "ലാബ്", "CAMPUS_TERM", "lab_loanword"),
    VocabEntry("lab", "*", "laboratory", "CAMPUS_TERM", "lab_english"),
    VocabEntry("room", "kn", "ಕೊಠಡಿ", "CAMPUS_TERM", "room"),
    VocabEntry("room", "kn", "ರೂಮ್", "CAMPUS_TERM", "room_loanword"),
    VocabEntry("room", "hi", "कमरा", "CAMPUS_TERM", "room"),
    VocabEntry("room", "hi", "रूम", "CAMPUS_TERM", "room_loanword"),
    VocabEntry("room", "te", "గది", "CAMPUS_TERM", "room"),
    VocabEntry("room", "te", "రూమ్", "CAMPUS_TERM", "room_loanword"),
    VocabEntry("room", "ta", "அறை", "CAMPUS_TERM", "room"),
    VocabEntry("room", "ta", "ரூம்", "CAMPUS_TERM", "room_loanword"),
    VocabEntry("room", "ml", "മുറി", "CAMPUS_TERM", "room"),
    VocabEntry("room", "ml", "റൂം", "CAMPUS_TERM", "room_loanword"),
    VocabEntry("cabin", "kn", "ಕ್ಯಾಬಿನ್", "CAMPUS_TERM", "cabin_loanword"),
    VocabEntry("cabin", "hi", "केबिन", "CAMPUS_TERM", "cabin_loanword"),
    VocabEntry("cabin", "te", "క్యాబిన్", "CAMPUS_TERM", "cabin_loanword"),
    VocabEntry("cabin", "ta", "கேபின்", "CAMPUS_TERM", "cabin_loanword"),
    VocabEntry("cabin", "ml", "ക്യാബിൻ", "CAMPUS_TERM", "cabin_loanword"),
    VocabEntry("cabin", "*", "cabin", "CAMPUS_TERM", "cabin_english"),
    VocabEntry("chamber", "kn", "ಚೇಂಬರ್", "CAMPUS_TERM", "chamber_loanword"),
    VocabEntry("chamber", "hi", "चैंबर", "CAMPUS_TERM", "chamber_loanword"),
    VocabEntry("chamber", "te", "ఛాంబర్", "CAMPUS_TERM", "chamber_loanword"),
    VocabEntry("chamber", "ta", "சேம்பர்", "CAMPUS_TERM", "chamber_loanword"),
    VocabEntry("chamber", "ml", "ചേമ്പർ", "CAMPUS_TERM", "chamber_loanword"),
    VocabEntry("chamber", "*", "chamber", "CAMPUS_TERM", "chamber_english"),
    VocabEntry("office", "kn", "ಕಚೇರಿ", "CAMPUS_TERM", "office"),
    VocabEntry("office", "kn", "ಆಫೀಸ್", "CAMPUS_TERM", "office_loanword"),
    VocabEntry("office", "hi", "कार्यालय", "CAMPUS_TERM", "office"),
    VocabEntry("office", "hi", "ऑफिस", "CAMPUS_TERM", "office_loanword"),
    VocabEntry("office", "te", "కార్యాలయం", "CAMPUS_TERM", "office"),
    VocabEntry("office", "te", "ఆఫీస్", "CAMPUS_TERM", "office_loanword"),
    VocabEntry("office", "ta", "அலுவலகம்", "CAMPUS_TERM", "office"),
    VocabEntry("office", "ta", "ஆபிஸ்", "CAMPUS_TERM", "office_loanword"),
    VocabEntry("office", "ml", "ഓഫീസ്", "CAMPUS_TERM", "office_loanword"),
    VocabEntry("office", "*", "office", "CAMPUS_TERM", "office_english"),
    VocabEntry("hall", "kn", "ಹಾಲ್", "CAMPUS_TERM", "hall_loanword"),
    VocabEntry("hall", "hi", "हॉल", "CAMPUS_TERM", "hall_loanword"),
    VocabEntry("hall", "te", "హాల్", "CAMPUS_TERM", "hall_loanword"),
    VocabEntry("hall", "ta", "ஹால்", "CAMPUS_TERM", "hall_loanword"),
    VocabEntry("hall", "ml", "ഹാൾ", "CAMPUS_TERM", "hall_loanword"),
    VocabEntry("hall", "*", "hall", "CAMPUS_TERM", "hall_english"),
    VocabEntry("counter", "kn", "ಕೌಂಟರ್", "CAMPUS_TERM", "counter_loanword"),
    VocabEntry("counter", "hi", "काउंटर", "CAMPUS_TERM", "counter_loanword"),
    VocabEntry("counter", "te", "కౌంటర్", "CAMPUS_TERM", "counter_loanword"),
    VocabEntry("counter", "ta", "கவுண்டர்", "CAMPUS_TERM", "counter_loanword"),
    VocabEntry("counter", "ml", "കൗണ്ടർ", "CAMPUS_TERM", "counter_loanword"),
    VocabEntry("center", "kn", "ಸೆಂಟರ್", "CAMPUS_TERM", "center_loanword"),
    VocabEntry("center", "hi", "सेंटर", "CAMPUS_TERM", "center_loanword"),
    VocabEntry("center", "*", "centre", "CAMPUS_TERM", "centre_english"),
    VocabEntry("block", "kn", "ಬ್ಲಾಕ್", "CAMPUS_TERM", "block_loanword"),
    VocabEntry("block", "hi", "ब्लॉक", "CAMPUS_TERM", "block_loanword"),
    VocabEntry("block", "te", "బ్లాక్", "CAMPUS_TERM", "block_loanword"),
    VocabEntry("block", "ta", "பிளாக்", "CAMPUS_TERM", "block_loanword"),
    VocabEntry("block", "ml", "ബ്ലോക്ക്", "CAMPUS_TERM", "block_loanword"),
    VocabEntry("department", "kn", "ವಿಭಾಗ", "CAMPUS_TERM", "department"),
    VocabEntry("department", "hi", "विभाग", "CAMPUS_TERM", "department"),
    VocabEntry("department", "te", "విభాగం", "CAMPUS_TERM", "department"),
    VocabEntry("department", "ta", "துறை", "CAMPUS_TERM", "department"),
    VocabEntry("department", "ml", "വിഭാഗം", "CAMPUS_TERM", "department"),
    VocabEntry("department", "kn", "ಡಿಪಾರ್ಟ್‌ಮೆಂಟ್", "CAMPUS_TERM", "department_loanword"),
    VocabEntry("principal", "kn", "ಪ್ರಾಂಶುಪಾಲರು", "CAMPUS_TERM", "principal"),
    VocabEntry("principal", "kn", "ಪ್ರಾಂಶುಪಾಲರ", "CAMPUS_TERM", "principal"),
    VocabEntry("principal", "kn", "ಪ್ರಿನ್ಸಿಪಲ್", "CAMPUS_TERM", "principal_loanword"),
    VocabEntry("principal", "hi", "प्राचार्य", "CAMPUS_TERM", "principal"),
    VocabEntry("principal", "hi", "प्रिंसिपल", "CAMPUS_TERM", "principal_loanword"),
    VocabEntry("principal", "te", "ప్రిన్సిపల్", "CAMPUS_TERM", "principal_loanword"),
    VocabEntry("principal", "te", "ప్రిన్సిపాల్", "CAMPUS_TERM", "principal_loanword"),
    VocabEntry("principal", "ta", "முதல்வர்", "CAMPUS_TERM", "principal"),
    VocabEntry("principal", "ta", "பிரின்சிபல்", "CAMPUS_TERM", "principal_loanword"),
    VocabEntry("principal", "ml", "പ്രിൻസിപ്പൽ", "CAMPUS_TERM", "principal_loanword"),
    VocabEntry("principal", "*", "principle", "CAMPUS_TERM", "principal_stt"),
    VocabEntry("hod", "kn", "ವಿಭಾಗದ ಮುಖ್ಯಸ್ಥ", "CAMPUS_TERM", "hod"),
    VocabEntry("hod", "hi", "विभागाध्यक्ष", "CAMPUS_TERM", "hod"),
    VocabEntry("hod", "te", "విభాగం అధిపతి", "CAMPUS_TERM", "hod"),
    VocabEntry("hod", "ta", "துறைத் தலைவர்", "CAMPUS_TERM", "hod"),
    VocabEntry("hod", "ml", "വിഭാഗത്തിന്റെ മേധാവി", "CAMPUS_TERM", "hod"),
    VocabEntry("hod", "*", "h.o.d", "CAMPUS_TERM", "hod_abbrev"),
    VocabEntry("library", "kn", "ಗ್ರಂಥಾಲಯ", "CAMPUS_TERM", "library"),
    VocabEntry("library", "kn", "ಲೈಬ್ರರಿ", "CAMPUS_TERM", "library_loanword"),
    VocabEntry("library", "hi", "पुस्तकालय", "CAMPUS_TERM", "library"),
    VocabEntry("library", "hi", "लाइब्रेरी", "CAMPUS_TERM", "library_loanword"),
    VocabEntry("library", "te", "గ్రంథాలయం", "CAMPUS_TERM", "library"),
    VocabEntry("library", "te", "లైబ్రరీ", "CAMPUS_TERM", "library_loanword"),
    VocabEntry("library", "ta", "நூலகம்", "CAMPUS_TERM", "library"),
    VocabEntry("library", "ta", "லைப்ரரி", "CAMPUS_TERM", "library_loanword"),
    VocabEntry("library", "ml", "ലൈബ്രറി", "CAMPUS_TERM", "library_loanword"),
    VocabEntry("admissions", "kn", "ಪ್ರವೇಶ", "CAMPUS_TERM", "admissions"),
    VocabEntry("admissions", "hi", "प्रवेश", "CAMPUS_TERM", "admissions"),
    VocabEntry("admissions", "te", "ప్రవేశ", "CAMPUS_TERM", "admissions"),
    VocabEntry("admissions", "ta", "சேர்க்கை", "CAMPUS_TERM", "admissions"),
    VocabEntry("admissions", "ml", "പ്രവേശനം", "CAMPUS_TERM", "admissions"),
    VocabEntry("admissions", "*", "admission", "CAMPUS_TERM", "admission_english"),
    VocabEntry("seminar", "kn", "ಸೆಮಿನಾರ್", "CAMPUS_TERM", "seminar_loanword"),
    VocabEntry("seminar", "hi", "सेमिनार", "CAMPUS_TERM", "seminar_loanword"),
    VocabEntry("seminar", "te", "సెమినార్", "CAMPUS_TERM", "seminar_loanword"),
    VocabEntry("seminar", "ta", "செமினார்", "CAMPUS_TERM", "seminar_loanword"),
    VocabEntry("seminar", "ml", "സെമിനാർ", "CAMPUS_TERM", "seminar_loanword"),
    VocabEntry("canteen", "kn", "ಕ್ಯಾಂಟೀನ್", "CAMPUS_TERM", "canteen_loanword"),
    VocabEntry("canteen", "hi", "कैंटीन", "CAMPUS_TERM", "canteen_loanword"),
    VocabEntry("canteen", "te", "కాంటీన్", "CAMPUS_TERM", "canteen_loanword"),
    VocabEntry("canteen", "ta", "கேண்டீன்", "CAMPUS_TERM", "canteen_loanword"),
    VocabEntry("canteen", "ml", "കാന്റീൻ", "CAMPUS_TERM", "canteen_loanword"),
    VocabEntry("hostel", "kn", "ಹಾಸ್ಟೆಲ್", "CAMPUS_TERM", "hostel_loanword"),
    VocabEntry("hostel", "hi", "हॉस्टल", "CAMPUS_TERM", "hostel_loanword"),
    VocabEntry("hostel", "te", "హాస్టల్", "CAMPUS_TERM", "hostel_loanword"),
    VocabEntry("hostel", "ta", "ஹாஸ்டல்", "CAMPUS_TERM", "hostel_loanword"),
    VocabEntry("hostel", "ml", "ഹോസ്റ്റൽ", "CAMPUS_TERM", "hostel_loanword"),
    VocabEntry("GF", "en", "ground floor", "CAMPUS_FLOOR", "floor"),
    VocabEntry("GF", "kn", "ನೆಲ ಮಹಡಿ", "CAMPUS_FLOOR", "floor"),
    VocabEntry("GF", "hi", "भूतल", "CAMPUS_FLOOR", "floor"),
    VocabEntry("GF", "te", "గ్రౌండ్ ఫ్లోర్", "CAMPUS_FLOOR", "floor"),
    VocabEntry("GF", "ta", "தரைத்தளம்", "CAMPUS_FLOOR", "floor"),
    VocabEntry("GF", "ml", "താഴത്തെ നില", "CAMPUS_FLOOR", "floor"),
    VocabEntry("FF", "en", "first floor", "CAMPUS_FLOOR", "floor"),
    VocabEntry("FF", "kn", "ಮೊದಲ ಮಹಡಿ", "CAMPUS_FLOOR", "floor"),
    VocabEntry("FF", "hi", "पहली मंजिल", "CAMPUS_FLOOR", "floor"),
    VocabEntry("FF", "te", "మొదటి అంతస్తు", "CAMPUS_FLOOR", "floor"),
    VocabEntry("FF", "ta", "முதல் தளம்", "CAMPUS_FLOOR", "floor"),
    VocabEntry("FF", "ml", "ഒന്നാം നില", "CAMPUS_FLOOR", "floor"),
    VocabEntry("SF", "en", "second floor", "CAMPUS_FLOOR", "floor"),
    VocabEntry("SF", "kn", "ಎರಡನೇ ಮಹಡಿ", "CAMPUS_FLOOR", "floor"),
    VocabEntry("SF", "hi", "दूसरी मंजिल", "CAMPUS_FLOOR", "floor"),
    VocabEntry("SF", "te", "రెండవ అంతస్తు", "CAMPUS_FLOOR", "floor"),
    VocabEntry("SF", "ta", "இரண்டாம் தளம்", "CAMPUS_FLOOR", "floor"),
    VocabEntry("SF", "ml", "രണ്ടാം നില", "CAMPUS_FLOOR", "floor"),
    # --- TOPIC: fees (English + existing production native/romanized cues) ---
    VocabEntry("fees", "en", "fees", "TOPIC", "english_topic"),
    VocabEntry("fees", "en", "fee", "TOPIC", "english_topic"),
    VocabEntry("fees", "en", "tuition", "TOPIC", "english_topic"),
    VocabEntry("fees", "en", "fee structure", "TOPIC", "english_topic"),
    VocabEntry("fees", "*", "yestu", "ROMANIZED", "kannada_how_much"),
    VocabEntry("fees", "*", "estu", "ROMANIZED", "kannada_how_much"),
    VocabEntry("fees", "*", "eshtu", "ROMANIZED", "kannada_how_much"),
    VocabEntry("fees", "*", "kitna", "ROMANIZED", "hindi_how_much"),
    VocabEntry("fees", "*", "evlo", "ROMANIZED", "tamil_how_much"),
    VocabEntry("fees", "*", "entha", "ROMANIZED", "telugu_how_much"),
    VocabEntry("fees", "*", "ethra", "ROMANIZED", "malayalam_how_much"),
    VocabEntry("fees", "*", "kattanam", "ROMANIZED", "tamil_fee_word"),
    VocabEntry("fees", "kn", "ಶುಲ್ಕ", "TOPIC", "kannada_script_fee"),
    VocabEntry("fees", "kn", "ಶುಲ್ಕಗಳು", "TOPIC", "kannada_script_fee"),
    VocabEntry("fees", "kn", "ಫೀಸ್", "TOPIC", "kannada_script_fee"),
    VocabEntry("fees", "hi", "फीस", "TOPIC", "hindi_script_fee"),
    VocabEntry("fees", "hi", "शुल्क", "TOPIC", "hindi_script_fee"),
    VocabEntry("fees", "ta", "கட்டணம்", "TOPIC", "tamil_script_fee"),
    VocabEntry("fees", "te", "ఫీజు", "TOPIC", "telugu_script_fee"),
    VocabEntry("fees", "ml", "ഫീസ്", "TOPIC", "malayalam_script_fee"),
    # --- TOPIC: HOD ---
    VocabEntry("hod", "en", "hod", "TOPIC", "english_topic"),
    VocabEntry("hod", "en", "h o d", "TOPIC", "english_stt_spaced_acronym"),
    VocabEntry("hod", "en", "hods", "TOPIC", "english_topic_plural"),
    VocabEntry("hod", "en", "head of department", "TOPIC", "english_topic"),
    VocabEntry("hod", "en", "head of the department", "TOPIC", "english_topic"),
    VocabEntry("hod", "en", "head of", "TOPIC", "english_topic"),
    VocabEntry("hod", "kn", "ಮುಖ್ಯಸ್ಥರು", "TOPIC", "kannada_script_hod"),
    VocabEntry("hod", "kn", "ಮುಖ್ಯಸ್ಥ", "TOPIC", "kannada_script_hod"),
    VocabEntry("hod", "kn", "ವಿಭಾಗದ ಮುಖ್ಯಸ್ಥರು", "TOPIC", "kannada_script_hod"),
    # Observed Kannada browser-STT variants of HOD / head of department.
    VocabEntry("hod", "kn", "ಹೋಡ್", "TOPIC", "kannada_stt_hod"),
    VocabEntry("hod", "kn", "ಹೆಡ್", "TOPIC", "kannada_stt_head"),
    VocabEntry("hod", "kn", "ಹೆಚ್ಒಡಿ", "TOPIC", "kannada_stt_hod_spelled"),
    VocabEntry("hod", "kn", "ಹೆಚ್ಓಡಿ", "TOPIC", "kannada_stt_hod_spelled"),
    VocabEntry("hod", "kn", "ವಿಭಾಗದ ಹೆಡ್", "TOPIC", "kannada_stt_department_head"),
    VocabEntry("hod", "kn", "ಸಚಿವರು", "TOPIC", "kannada_stt_hod_misrecognition", "high"),
    VocabEntry("hod", "kn", "ಸಚಿವ", "TOPIC", "kannada_stt_hod_minister"),
    VocabEntry("hod", "hi", "विभागाध्यक्ष", "TOPIC", "hindi_locale_hod_title"),
    VocabEntry("hod", "hi", "विभाग प्रमुख", "TOPIC", "hindi_script_hod"),
    VocabEntry("hod", "hi", "विभाग के प्रमुख", "TOPIC", "hindi_script_hod_postposition"),
    VocabEntry("hod", "hi", "एचओडी", "TOPIC", "hindi_stt_hod_spelled"),
    VocabEntry("hod", "hi", "एच ओ डी", "TOPIC", "hindi_stt_hod_spaced"),
    VocabEntry("hod", "hi", "होद", "TOPIC", "hindi_stt_hod_phonetic"),
    VocabEntry("hod", "ta", "துறைத் தலைவர்", "TOPIC", "tamil_locale_hod_title"),
    VocabEntry("hod", "te", "విభాగం అధిపతి", "TOPIC", "telugu_locale_hod_title"),
    VocabEntry("hod", "ml", "വിഭാഗത്തിന്റെ മേധാവി", "TOPIC", "malayalam_locale_hod_title"),
    VocabEntry("hod", "kn", "ಎಚ್ ಓ ಡಿ", "TOPIC", "kannada_stt_hod_spelled"),
    VocabEntry("hod", "kn", "ಹೆಚ್ ಓ ಡಿ", "TOPIC", "kannada_stt_hod_spelled"),
    VocabEntry("hod", "*", "yaaru", "QUESTION", "kannada_who", "low"),
    VocabEntry("hod", "*", "yaar", "QUESTION", "tamil_who", "low"),
    VocabEntry("hod", "*", "kaun", "QUESTION", "hindi_who", "low"),
    VocabEntry("hod", "*", "evaru", "QUESTION", "telugu_who", "low"),
    VocabEntry("hod", "*", "aaranu", "QUESTION", "malayalam_who", "low"),
    # --- TOPIC: overview (explicit word only; generic "about" stays a SCOPE cue) ---
    VocabEntry("overview", "en", "overview", "TOPIC", "english_topic"),
    VocabEntry("overview", "en", "over view", "TOPIC", "english_topic"),
    VocabEntry("overview", "kn", "ಅವಲೋಕನ", "TOPIC", "kannada_script_overview"),
    VocabEntry("overview", "hi", "अवलोकन", "TOPIC", "hindi_script_overview"),
    VocabEntry("overview", "ta", "கண்ணோட்டம்", "TOPIC", "tamil_script_overview"),
    VocabEntry("overview", "te", "అవలోకనం", "TOPIC", "telugu_script_overview"),
    VocabEntry("overview", "ml", "അവലോകനം", "TOPIC", "malayalam_script_overview"),
    # --- TOPIC: placements ---
    VocabEntry("placements", "en", "placements", "TOPIC", "english_topic"),
    VocabEntry("placements", "en", "placement", "TOPIC", "english_topic"),
    VocabEntry("placements", "kn", "ಪ್ಲೇಸ್‌ಮೆಂಟ್", "TOPIC", "kannada_script_placement"),
    VocabEntry("placements", "kn", "ಪ್ಲೇಸ್ಮೆಂಟ್", "TOPIC", "kannada_script_placement"),
    VocabEntry("placements", "kn", "ಉದ್ಯೋಗಾವಕಾಶ", "TOPIC", "kannada_script_placement"),
    VocabEntry("placements", "hi", "प्लेसमेंट", "TOPIC", "hindi_script_placement"),
    VocabEntry("placements", "ta", "பிளேஸ்மென்ட்", "TOPIC", "tamil_script_placement"),
    VocabEntry("placements", "ta", "வேலைவாய்ப்பு", "TOPIC", "tamil_script_placement"),
    VocabEntry("placements", "te", "ప్లేస్‌మెంట్", "TOPIC", "telugu_script_placement"),
    VocabEntry("placements", "ml", "പ്ലേസ്‌മെന്റ്", "TOPIC", "malayalam_script_placement"),
    VocabEntry("placements", "ml", "പ്ലേസ്മെന്റ്", "TOPIC", "malayalam_script_placement"),
    # These concepts are parsed even when a deployment has no corresponding
    # ContentUnit. Unit selection can then report CARD_NOT_REGISTERED instead of
    # silently opening the department overview.
    VocabEntry("faculty", "en", "faculty", "TOPIC", "english_topic"),
    VocabEntry("faculty", "en", "teachers", "TOPIC", "english_topic"),
    VocabEntry("faculty", "kn", "ಬೋಧಕರು", "TOPIC", "kannada_script_faculty"),
    VocabEntry("faculty", "hi", "शिक्षक", "TOPIC", "hindi_script_faculty"),
    VocabEntry("faculty", "hi", "अध्यापक", "TOPIC", "hindi_script_faculty"),
    VocabEntry("faculty", "hi", "फैकल्टी", "TOPIC", "hindi_script_faculty_loanword"),
    VocabEntry("faculty", "te", "అధ్యాపకులు", "TOPIC", "telugu_script_faculty"),
    VocabEntry("faculty", "ta", "ஆசிரியர்கள்", "TOPIC", "tamil_script_faculty"),
    VocabEntry("faculty", "ml", "അധ്യാപകർ", "TOPIC", "malayalam_script_faculty"),
    VocabEntry("contact", "en", "contact details", "TOPIC", "english_topic"),
    VocabEntry("contact", "en", "contact", "TOPIC", "english_topic"),
    VocabEntry("contact", "kn", "ಸಂಪರ್ಕ", "TOPIC", "kannada_script_contact"),
    VocabEntry("contact", "hi", "संपर्क", "TOPIC", "hindi_script_contact"),
    VocabEntry("contact", "te", "సంప్రదింపు", "TOPIC", "telugu_script_contact"),
    VocabEntry("contact", "ta", "தொடர்பு", "TOPIC", "tamil_script_contact"),
    VocabEntry("contact", "ml", "ബന്ധപ്പെടാൻ", "TOPIC", "malayalam_script_contact"),
    # --- TOPIC: achievements (English-only in Stage A evidence; keep purpose-tagged) ---
    VocabEntry("achievements", "en", "achievements", "TOPIC", "english_topic"),
    VocabEntry("achievements", "en", "achievement", "TOPIC", "english_topic"),
    VocabEntry("achievements", "en", "rankings", "TOPIC", "english_topic"),
    VocabEntry("achievements", "en", "ranking", "TOPIC", "english_topic"),
    VocabEntry("achievements", "kn", "ಸಾಧನೆ", "TOPIC", "kannada_script_achievement"),
    VocabEntry("achievements", "hi", "उपलब्धि", "TOPIC", "hindi_script_achievement"),
    VocabEntry("achievements", "ta", "சாதனை", "TOPIC", "tamil_script_achievement"),
    VocabEntry("achievements", "te", "సాధన", "TOPIC", "telugu_script_achievement"),
    VocabEntry("achievements", "ml", "നേട്ടം", "TOPIC", "malayalam_script_achievement"),
    # --- SCOPE: full-department overview (not generic "about"/"overview") ---
    VocabEntry("full_department", "en", "tell me about", "SCOPE", "full_overview"),
    VocabEntry("full_department", "en", "tell me", "SCOPE", "full_overview"),
    VocabEntry("full_department", "en", "explain", "SCOPE", "full_overview"),
    VocabEntry("full_department", "en", "describe", "SCOPE", "full_overview"),
    VocabEntry("full_department", "*", "bagge", "CODE-SWITCH", "kannada_about"),
    VocabEntry("full_department", "*", "helu", "CODE-SWITCH", "kannada_tell"),
    VocabEntry("full_department", "*", "heli", "CODE-SWITCH", "kannada_tell"),
    VocabEntry("full_department", "*", "baare", "CODE-SWITCH", "hindi_about"),
    VocabEntry("full_department", "*", "batao", "CODE-SWITCH", "hindi_tell"),
    VocabEntry("full_department", "*", "pattri", "CODE-SWITCH", "tamil_about"),
    VocabEntry("full_department", "*", "tilisi", "CODE-SWITCH", "tamil_tell"),
    VocabEntry("full_department", "*", "gurunchi", "CODE-SWITCH", "telugu_about"),
    VocabEntry("full_department", "*", "gurinchi", "CODE-SWITCH", "telugu_about"),
    VocabEntry("full_department", "*", "kurichu", "CODE-SWITCH", "telugu_tell"),
    VocabEntry("full_department", "*", "parayoo", "CODE-SWITCH", "malayalam_tell"),
    VocabEntry("full_department", "*", "paray", "CODE-SWITCH", "malayalam_tell"),
    # --- UNSUPPORTED for unit selector ---
    VocabEntry("bus", "en", "bus routes", "UNSUPPORTED", "not_unit_owned"),
    VocabEntry("bus", "en", "bus route", "UNSUPPORTED", "not_unit_owned"),
    VocabEntry("documents", "en", "documents", "UNSUPPORTED", "not_unit_owned"),
    VocabEntry("documents", "en", "document", "UNSUPPORTED", "not_unit_owned"),
    # --- DEPARTMENT aliases (identity via exclusive longest-span, never substring) ---
    VocabEntry("cse_ds", "en", "cse data science", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_ds", "en", "cse (data science)", "DEPARTMENT", "canonical_label"),
    VocabEntry("cse_ds", "en", "cse datascience", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_ds", "en", "data science", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_ds", "en", "datascience", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_ds", "en", "cse ds", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_ds", "en", "cse_ds", "DEPARTMENT", "json_key"),
    VocabEntry("cse_ds", "kn", "ಡೇಟಾ ಸೈನ್ಸ್", "DEPARTMENT", "kannada_script_ds"),
    VocabEntry("cse_ds", "kn", "ಡೇಟಾ ಸಂಖ್ಯೆ", "DEPARTMENT", "kannada_stt_data_science_misrecognition", "high"),
    VocabEntry("cse_ds", "hi", "डेटा साइंस", "DEPARTMENT", "hindi_script_ds"),
    VocabEntry("cse_ds", "hi", "डेटा साइन्स", "DEPARTMENT", "hindi_script_ds_alt"),
    VocabEntry("cse_ds", "ta", "டேட்டா சயின்ஸ்", "DEPARTMENT", "tamil_script_ds"),
    VocabEntry("cse_ds", "ta", "டேட்டா சயன்ஸ்", "DEPARTMENT", "tamil_script_ds_alt"),
    VocabEntry("cse_ds", "te", "డేటా సైన్స్", "DEPARTMENT", "telugu_script_ds"),
    VocabEntry("cse_ds", "ml", "ഡാറ്റ സയൻസ്", "DEPARTMENT", "malayalam_common_name"),
    VocabEntry("cse_ds", "ml", "ഡാറ്റ സയൻസി", "DEPARTMENT", "malayalam_agglutinated_stem"),
    VocabEntry("cse_ds", "ml", "ഡാറ്റാ സയൻസ്", "DEPARTMENT", "malayalam_alt_spelling"),
    VocabEntry("cse_aiml", "en", "cse ai ml", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_aiml", "en", "cse (ai & ml)", "DEPARTMENT", "canonical_label"),
    VocabEntry("cse_aiml", "en", "cse aiml", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_aiml", "en", "ai ml", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_aiml", "en", "ai & ml", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_aiml", "en", "aiml", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_aiml", "en", "cse_aiml", "DEPARTMENT", "json_key"),
    VocabEntry("cse_cysec", "en", "cse cyber security", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_cysec", "en", "cyber security", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_cysec", "en", "cybersecurity", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_cysec", "en", "cse_cysec", "DEPARTMENT", "json_key"),
    VocabEntry("cse_bs", "en", "cse business systems", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_bs", "en", "business systems", "DEPARTMENT", "compound_identity"),
    VocabEntry("cse_bs", "en", "cse_bs", "DEPARTMENT", "json_key"),
    VocabEntry("cse", "en", "computer science and engineering", "DEPARTMENT", "full_name"),
    VocabEntry("cse", "en", "computer science & engineering", "DEPARTMENT", "full_name"),
    VocabEntry("cse", "en", "computer science engineering", "DEPARTMENT", "full_name"),
    VocabEntry("cse", "en", "computer science", "DEPARTMENT", "full_name"),
    VocabEntry("cse", "en", "cse", "DEPARTMENT", "acronym"),
    VocabEntry("cse", "en", "c s e", "DEPARTMENT", "english_stt_spaced_acronym"),
    VocabEntry("cse", "kn", "ಸಿಎಸ್ಇ", "DEPARTMENT", "kannada_script_acronym"),
    VocabEntry("cse", "kn", "ಸಿಎಸ್‌ಇ", "DEPARTMENT", "kannada_script_acronym"),
    VocabEntry("cse", "kn", "ಸಿಎಸ್ ಇ", "DEPARTMENT", "kannada_spaced_acronym"),
    VocabEntry("cse", "hi", "सीएसई", "DEPARTMENT", "hindi_script_acronym"),
    VocabEntry("cse", "hi", "सी एस ई", "DEPARTMENT", "hindi_spaced_acronym"),
    VocabEntry("cse", "hi", "कंप्यूटर साइंस", "DEPARTMENT", "hindi_common_name"),
    VocabEntry("ise", "en", "information science", "DEPARTMENT", "full_name"),
    VocabEntry("ise", "en", "ise", "DEPARTMENT", "acronym"),
    VocabEntry("ece", "en", "electronics", "DEPARTMENT", "full_name", "medium"),
    VocabEntry("ece", "en", "ece", "DEPARTMENT", "acronym"),
    VocabEntry("ece", "en", "e c e", "DEPARTMENT", "english_stt_spaced_acronym"),
    VocabEntry("ece", "hi", "ईसीई", "DEPARTMENT", "hindi_script_acronym"),
    VocabEntry("ece", "hi", "ई सी ई", "DEPARTMENT", "hindi_spaced_acronym"),
    VocabEntry("civil", "en", "civil", "DEPARTMENT", "acronym"),
    VocabEntry("mechanical", "en", "mechanical", "DEPARTMENT", "full_name"),
    VocabEntry("mechanical", "hi", "मेकेनिकल", "DEPARTMENT", "hindi_stt_variant"),
    VocabEntry("mechanical", "hi", "मैकैनिकल", "DEPARTMENT", "hindi_stt_variant"),
    VocabEntry("mba", "en", "mba", "DEPARTMENT", "acronym"),
    VocabEntry("mba", "hi", "एमबीए", "DEPARTMENT", "hindi_script_acronym"),
    VocabEntry("mba", "hi", "एम बी ए", "DEPARTMENT", "hindi_spaced_acronym"),
    VocabEntry("basic_sciences", "en", "basic sciences", "DEPARTMENT", "full_name"),
)


def all_entries() -> tuple[VocabEntry, ...]:
    return _ENTRIES


def entries_for(*, category: str | None = None, canonical: str | None = None) -> tuple[VocabEntry, ...]:
    rows = _ENTRIES
    if category:
        rows = tuple(e for e in rows if e.category == category)
    if canonical:
        rows = tuple(e for e in rows if e.canonical == canonical)
    return rows
