"""Institutional ANSWER cues — six languages, one matcher.

These are meaning-bearing campus words, not a translation of an English list.
`detect_domain_relevance` matches them with the same `cue_in_hay` used for CARD
topics: native script as substring, Latin/romanized as whole tokens.

Do not add generic question words (how, hegiddare, kaisa, eppadi) by themselves.
"""

from __future__ import annotations

# Natural campus vocabulary. Order does not matter. Duplicates across languages
# that share a loanword (campus, lab, wifi) appear once in Latin.
INSTITUTION_CUES: tuple[str, ...] = (
    # Faculty / teaching
    "hackathon",
    "hackathons",
    "club",
    "clubs",
    "fest",
    "fests",
    "experienced",
    "supportive",
    "makerspace",
    "adhyapaka",
    "shikshaka",
    "bodhane",
    "upadhyaya",
    "aasiriyar",
    "shikshak",
    "padhai",
    "ಅಧ್ಯಾಪಕ",
    "ಶಿಕ್ಷಕ",
    "ಟೀಚರ್",
    "ಬೋಧನೆ",
    "ಅನುಭವ",
    "शिक्षक",
    "टीचर",
    "फैकल्टी",
    "पढ़ाई",
    "अध्यापक",
    "ஆசிரியர்",
    "பேராசிரியர்",
    "படிப்பு",
    "ఉపాధ్యాయ",
    "టీచర్",
    "బోధన",
    "అనుభవం",
    "അധ്യാപക",
    "ടീച്ചർ",
    "ബോധന",
    # Campus life / environment
    "vatavarana",
    "vaatavarana",
    "soozhal",
    "vatavaranam",
    "vidyarthi",
    "chatra",
    "maanavar",
    "ಕ್ಯಾಂಪಸ್",
    "ಕಾಲೇಜು",
    "ವಿದ್ಯಾರ್ಥಿ",
    "ವಾತಾವರಣ",
    "ಜೀವನ",
    "कैंपस",
    "कॉलेज",
    "छात्र",
    "वातावरण",
    "जीवन",
    "வளாகம்",
    "கல்லூரி",
    "மாணவர்",
    "சூழல்",
    "క్యాంపస్",
    "కాలేజీ",
    "విద్యార్థి",
    "వాతావరణం",
    "ക്യാമ്പസ്",
    "കോളേജ്",
    "padippu",
    "chaduvu",
    "வளாக",
    "കോളേജി",
    "വിദ്യാർത്ഥി",
    "അന്തരീക്ഷം",
    # Facilities
    "granthalaya",
    "pustakalay",
    "noolagam",
    "ಗ್ರಂಥಾಲಯ",
    "ಪ್ರಯೋಗಾಲಯ",
    "ಪ್ರಯೋಗ",
    "ಲ್ಯಾಬ್",
    "ಕ್ರೀಡೆ",
    "ವೈಫೈ",
    "ಹಾಸ್ಟೆಲ್",
    "पुस्तकालय",
    "प्रयोगशाला",
    "लैब",
    "खेल",
    "वाईफाई",
    "हॉस्टल",
    "நூலகம்",
    "ஆய்வகம்",
    "லேப்",
    "விளையாட்டு",
    "வைஃபை",
    "హాస్టల్",
    "గ్రంథాలయం",
    "ప్రయోగశాల",
    "ల్యాబ్",
    "క్రీడ",
    "వైఫై",
    "ലൈബ്രറി",
    "ലാബ്",
    "കായിക",
    "വൈഫൈ",
    "ഹോസ്റ്റൽ",
    # Student experience / internships / placements / academics
    "ಹ್ಯಾಕಥಾನ್",
    "ಕ್ಲಬ್",
    "ಇಂಟರ್ನ್",
    "ಪ್ಲೇಸ್‌ಮೆಂಟ್",
    "ಪ್ಲೇಸ್ಮೆಂಟ್",
    "ನೇಮಕಾತಿ",
    "ಪಠ್ಯಕ್ರಮ",
    "ಯೋಜನೆ",
    "ಪ್ರಾಜೆಕ್ಟ್",
    "प्रोजेक्ट",
    "ப்ராஜெக்ட்",
    "ప్రాజెక్ట్",
    "പ്രോജക്റ്റ്",
    "हैकथॉन",
    "क्लब",
    "इंटर्न",
    "प्लेसमेंट",
    "पाठ्यक्रम",
    "ஹேக்கத்தான்",
    "சங்கம்",
    "இன்டர்ன்",
    "பிளேஸ்மென்ட்",
    "பாடத்திட்டம்",
    "హ్యాకథాన్",
    "క్లబ్",
    "ఇంటర్న్",
    "ప్లేస్‌మెంట్",
    "పాఠ్యాంశం",
    "ഹാക്കത്തോൺ",
    "ക്ലബ്",
    "ഇന്റേൺ",
    "പ്ലേസ്‌മെന്റ്",
    "പാഠ്യപദ്ധതി",
    # General institutional
    "svit",
    "ಸಾಯಿ ವಿದ್ಯಾ",
    "ಸ್ವಿಟ್",
    "साई विद्या",
    "சாயி வித்யா",
    "సాయి విద్యా",
    "സായി വിദ്യ",
)


def institution_cues() -> tuple[str, ...]:
    return INSTITUTION_CUES
